# Generated by Django 5.1.4 on 2025-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('date', models.CharField(max_length=5)),
                ('cvv', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='products', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
